apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: us-east-1

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-04f241f8844b9f82b }
      us-east-1b: { id: subnet-0377ea9d56d016ea7 }

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 1
    volumeSize: 20